export const FETCH_CURRENCIES = "FETCH_COUNTRIES";
export const FETCH_QUOTES = "FETCH_QUOTES";
export const SET_FIRST_CURRENCY = "SET_FIRST_CURRENCY";
export const SET_SECOND_CURRENCY = "SET_SECOND_CURRENCY";
export const SET_FIRST_AMOUNT = "SET_FIRST_AMOUNT";
export const SET_SECOND_AMOUNT = "SET_SECOND_AMOUNT";
